### ISSUE TITLE
Implement tagged template string

### ISSUE THREAD

**Issue by teohhanhui** [slevithan/xregexp#103]
As per your gist from 2012: https://gist.github.com/slevithan/4222600

**Comment by slevithan** [comment]
IMO this is not a priority until more browsers support tagged template strings natively.

Some changes in thinking since writing that gist:

* Not sure what the name of the tag should be, but probably not `r`. Maybe `XRegExp.make` or `XRegExp.create`. You could do <code>XRegExp.make(flags)\`...\`</code> to provide flags.
* Probably would want this to accept regexes as raw strings, but it make sense to support atomic regex/string interpolation (but not support flags for interpolated regexes).
* Would want to implicitly enable free-spacing, but also maybe implicitly enable "explicit capture" and ES6's unicode flag. Probably don't want to offer multiple tags with any variation of implicit flags.
* Would want to add `$<n>` and `$<name>` as alternative backreference syntax for `${n}` and `${name}` in replacement text, so they can be used in ES6 template strings. This would be backward compatible, since `$<` is currently an error in XRegExp replacement text.

**Comment by teohhanhui** [comment]
Do tagged template strings not work with a transpiler like Babel?

**Comment by slevithan** [comment]
I actually don't know whether it supports creation of arbitrary new tag functions. Of course, you can and should use Babel today to get raw strings and multiline strings. No XRegExp changes are needed for that.

**Comment by rauschma** [comment]
@slevithan A tagged template literal is just another way of making a function call: the first parameter is an Array with the static parts of the template literal, the remaining parameters are the dynamic `${}` parts of the template literal.

Thus, you can even write tag functions in ES5.

More info: http://exploringjs.com/es6/ch_template-literals.html#_implementing-tag-functions

**Comment by Kagami** [comment]
It's perfectly possible to use ```XRegExp(String.raw`^test\raw\slashes$`))``` btw.

**Comment by treyhunner** [comment]
Just chiming in to add that I'm most interested in seeing a special tag in XRegExp so that interpolated strings can be escaped. A `RegExp.escape` proposal was rejected by TC39 last year and it was suggested that a template tag with escaping on interpolation would be more safe than escaping combined with plain string concatenation. Further discussion of this is at benjamingr/RegExp.escape#37.

Until XRegExp supports escaping via a tag, I'll continue my search for a tag function that escapes interpolated strings for use in regular expressions.

**Comment by josephfrazier** [comment]
Over at [OctoLinker/browser-extension#282](https://github.com/OctoLinker/browser-extension/pull/282/files#diff-0d6e17f4d5963a6cab3946c32ce6c976), I've made some progress on an `XRegExp.build`-backed implementation of a tag function that interpolates regular expressions and strings as described [above](https://github.com/slevithan/xregexp/issues/103#issuecomment-143148666), and it seems to work pretty well so far. @slevithan, would be interested in a pull request that adds it to the `build` addon?

Note that template literals are now [supported](https://devdocs.io/javascript/template_literals) natively in most browsers except IE, but Babel can [transpile](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&experimental=false&loose=false&spec=false&code=var%20s%20%3D%20String.raw%60prefix%20%5Cn%20%24%7B%2Finterpolated%2F%7D%20%5Cn%20suffix%60%0A%0Aconsole.log(s)&playground=true) them down to regular function calls (as mentioned [above](https://github.com/slevithan/xregexp/issues/103#issuecomment-166447382)), so they can work in IE as well.

**Comment by slevithan** [comment]
> would you be interested in a pull request that adds it to the build addon?

Yes, interested.
