### ISSUE TITLE
Inconsistent with Hindi Language

### ISSUE THREAD

**Issue by NaveenKY** [slevithan/xregexp#111]
When i try to test for Hindi Language it doesn't work properly. Can you please add support for Hindi also.

Below is the sample that i was trying....

```js
var unicodeWord = XRegExp("^\\p{L}+$");
console.log(unicodeWord.test("नवीन"));
```

**Comment by slevithan** [comment]
XRegExp is following the Unicode standard correctly.

Use any of the following, which all return `true`:

- `XRegExp('^[\\pL\\pM]+$').test('नवीन')`
- `XRegExp('^[\\pL\\p{Mc}]+$').test('नवीन')`
- `XRegExp('^\\p{Devanagari}+$').test('नवीन')`

The issue is that your string contains the spacing mark `U+0940`. See https://codepoints.net/U+0940?lang=en for more details.
