### ISSUE TITLE
Use of RegExp.prototype getters to determine support is invalid

### ISSUE THREAD

**Issue by marcins** [slevithan/xregexp#121]
In Chrome Canary 49.0.2583.0 with "Experimental JavaScript" enabled XRegExp throws an error because it tries to read `RegExp.prototype.sticky`.  Canary's behaviour is actually correct according to the ES2015 spec: http://www.ecma-international.org/ecma-262/6.0/#sec-get-regexp.prototype.sticky

An alternative method should be use to determine whether native support for certain RegExp features are available.

**Comment by slevithan** [comment]
@marcins Can you confirm whether you have this problem with XRegExp 3.0.0? You should not, since XRegExp 3.0.0 changed how support for the native /y flag is detected, to follow ES6.

(At the time of release, `RegExp.prototype.sticky` was not yet causing problems in any known browsers, and had been working in Firefox since the flag was introduced in 2008.)

**Comment by marcins** [comment]
Apologies, you're right, turns out we were running off a "3.0.0-pre" commit hash from 2012. I bumped the version to 3.0.0 in our app and it appears to now work correctly in Canary with Experimental JS enabled.

**Comment by slevithan** [comment]
Sweet. You should also get some other benefits with the upgrade including performance improvements. Props to @mathiasbynens for previously identifying and fixing the bug.
