### ISSUE TITLE
Not consistent with native regular expressions

### ISSUE THREAD

**Issue by 2426021684** [slevithan/xregexp#126]
```javascript
var r1 = new RegExp("\\u") // No error in Safari, Firefox, and Chrome
var r2 = new XRegExp("\\u") // Error Invalid Escape Sequence
```
Is this difference intentional?

**Comment by mathiasbynens** [comment]
`RegExp('\\u', 'u')` or `/\u/u` is an error, though. It [couldn’t be made an error](https://mathiasbynens.be/notes/es6-unicode-regex#impact-syntax) for existing regular expressions since that would have been a breaking change.

IMHO it’s fine that XRegExp is more strict about this (with or without the `u` flag). You shouldn’t escape things that don’t need escaping.

**Comment by slevithan** [comment]
Yes, this is intentional, for the reason @mathiasbynens mentioned. See http://xregexp.com/syntax/#strictErrors for details.

> XRegExp makes any escaped letters or numbers a `SyntaxError` unless they form a valid and complete metasequence or backreference. This helps to catch errors early, and makes it safe for future versions of ES or XRegExp to introduce new escape sequences. It also means that octal escapes are always an error in XRegExp. ES3/5 do not allow octal escapes, but browsers support them anyway for backward compatibility, which often leads to unintended behavior.
>
> XRegExp requires all backreferences, whether written as `\n`, `\k<n>`, or `\k<name>`, to appear to the right of the opening parenthesis of the group they reference.
>
> XRegExp never allows `\n`-style backreferences to be followed by literal numbers. To match backreference one followed by a literal `2` character, you can use, e.g., `(a)\k<1>2`, `(?x)(a)\1 2`, or `(a)\1(?#)2`.
