### ISSUE TITLE
Backreferences in character classes don't work

### ISSUE THREAD

**Issue by lencioni** [slevithan/xregexp#133]
I have the following regex that I want to match quoted bits in a string:

```js
const r = xRegExp(`(?<quote>['"])[^\\k<quote>]+\\k<quote>`);
```

but this produces an error like:

> SyntaxError: Invalid escape \k

So, I converted this to use numbered backreferences:

```js
const r = xRegExp(`(['"])[^\\1]+\\1`);
```

but this gives the following error:

> SyntaxError: Cannot use octal escape or backreference to undefined group \1

If I change the regex to remove the character class (this doesn't do what I want, but it illustrates the problem):

```js
const r = xRegExp(`(['"])^\\1+\\1`);
```

Then it is successfully transpiled to:

```js
/(['"])^\1+\1/
```

I have verified that the numbered backreference works with a normal RegExp:

```js
const r = new RegExp(`(['"])[^\\1]+\\1`);
```

In this case, the character class was just an optimization here and I can achieve my goal by using `.+?` instead, but I figured I'd write this up here in case it is useful.

**Comment by slevithan** [comment]
This is correct/expected behavior. Regex syntax within character classes is different than outside, and backreferences are among the features not supported within character classes. This is because character classes match only a single character, and backreferences can match any number of characters. This works the same way in all regex flavors that support backreferences, including native JavaScript.

In native JavaScript, `\1` within a character class matches octal character 1, which is the same as `\x01`. ECMAScript 3 and later deprecated use of octals in regular expressions. XRegExp also doesn't allow use of octals due to their overlapping syntax with backreferences.

**Comment by lencioni** [comment]
Are you sure? This is what I get in the Chrome console:

```
/('|")[^\1]+\1/.test('foo "bar" baz')
true
```

**Comment by abozhilov** [comment]
You got behavior that @slevithan has already explained. It returns true because the string does not contain character `\x01`. 

Let me illustrate: 

```
/(a)[^\1]/.test('aa'); // true 
```

```
/(a)[^\1]/.test('a\x01') //false 
```

Would be interesting in strict mode. I'll expect SyntaxError since there is octal escape.

**Comment by lencioni** [comment]
@abozhilov in your false example, that doesn't match because there are not two "a" characters next to each other as the regex expects. This is true:

```
/(a)[^\1]/.test('aa\x01') // true
```

**Comment by abozhilov** [comment]
No! Look closer both examples. Especially the first one.

**Comment by lencioni** [comment]
Ah, of course. I see it now. Thanks for your patience with me. :)

To better illustrate, here's another example:

```js
/('|")[^\1]+\1/.test('"foo\x01"') // false
```

**Comment by slevithan** [comment]
This confusion is a big part of why XRegExp always makes octal escapes an error.

**Comment by lencioni** [comment]
Yes, it makes complete sense! Thanks again!
