### ISSUE TITLE
Safari Technology Preview: 'sticky' error

### ISSUE THREAD

**Issue by gpbmike** [slevithan/xregexp#135]
Using Safari Technology Preview I get the following error:

```
null is not an object (evaluating 'XRegExp.exec(appliedPattern, nativeTokens[scope], pos, 'sticky')')
```

It is thrown by the following line:

```javascript
var token = XRegExp.exec(appliedPattern, nativeTokens[scope], pos, 'sticky')[0];
```

To replicate I copied https://github.com/slevithan/xregexp/blob/master/xregexp-all.js and threw it into a codepen. No other JS was added.

http://codepen.io/gpbmike/pen/BKENOg

Open up the developer console and you can see the error.

**Comment by slevithan** [comment]
Took me a while to identify the root cause because this seemed to be behaving randomly depending on the source regex and string. Turns out that Safari Technology Preview (tested v9.1.1) has a bad bug in its handling of the ES6 regex `y` flag.

```
/a|b/y.test('a'); // -> true
/a|b/y.test('b'); // -> true
/b|a/y.test('a'); // -> true
/b|a/y.test('b'); // -> true
/aa|bb/y.test('aa'); // -> true
/aa|bb/y.test('bb'); // -> true
/bb|aa/y.test('aa'); // -> true
/bb|aa/y.test('bb'); // -> true
/a|bb/y.test('a'); // -> true
/a|bb/y.test('bb'); // -> true
/bb|a/y.test('bb'); // -> true
/bb|a/y.test('a'); // -> false [should be true]
```

If a regex with flag `y` evaluates a path within a regex with more than 1 character, it advances its internal `lastIndex` that the `y` flag is anchored to, and does not reset this position when the alternative fails and another path in the regex with fewer characters to match is tried. Or something along those lines.

I've attempted to to report this bug to Apple, but their bug reporter gives me an unknown error upon sign in even though I've accepted the Apple developer agreement and gone through other hoops. I've send them an email about this. :-/

In the mean time I can test for this bug, and when it exists act like the browser doesn't support flag `y`. But that feels pretty bad since I'm testing for a browser/version specific bug and not actually testing a capability.

**Comment by slevithan** [comment]
For posterity, I'll note that Safari 9.1 does not have this issue, since 9.1.1 is the first version to support `/y`.

**Comment by gpbmike** [comment]
I appreciate you looking into that. I would not have expected a patch for a bug in an unstable browser. :+1:

**Comment by slevithan** [comment]
I patched it based on the severity of how it breaks XRegExp. If this bug never makes it into a stable Safari release, I'll remove the patch.

**Comment by mathiasbynens** [comment]
FWIW @slevithan, since this is a bug in JSC you could report the bug on https://bugs.webkit.org/ rather than bugreport.apple.com.

**Comment by slevithan** [comment]
Thanks @mathiasbynens. Filed at <https://bugs.webkit.org/show_bug.cgi?id=157723>.
