### ISSUE TITLE
Is the Xregexp syntax compatible with Oniguruma? 

### ISSUE THREAD

**Issue by megastef** [slevithan/xregexp#140]
Hi, we are interested in replace Onigurma with XRegExp, which is ued by Logstash as well and node-grok. I wonder if the GROK patterns would work after they got converted to Oniguruma syntax. 

https://github.com/kkos/oniguruma/blob/master/doc/RE

**Comment by nyxtom** [comment]
@megastef I was actually having trouble with this conversion. Not quite sure whether XRegExp supports atomic groups or whether the patterns are a bit messed up and not necessarily everything will work out of the box. I'm still investigating at the moment however.

**Comment by slevithan** [comment]
@nyxtom That's correct. XRegExp doesn't currently support atomic groups and possessive quantifiers. FYI though, technically it would be possible to build support for them since lookahead is atomic, and you can use backreferences to matches captured within lookahead. It would just be hard to make it work for regexes that don't use the n flag, because you would have to adjust for the renumbering of captures to the right of the atomic group or possessive quantifier.

@megastef you can learn more about XRegExp's non-native-JS syntax at <http://xregexp.com/syntax/>. XRegExp supports fewer features than Oniguruma.

**Comment by megastef** [comment]
Thx for the info!
