### ISSUE TITLE
Bug in escaping $ for replace

### ISSUE THREAD

**Issue by joshbw** [slevithan/xregexp#188]
If I do a normal match for \\$\_REQUEST it will match the php code $\_REQUEST without issue.  If I do a replace with \\$\_REQUEST as the pattern it somehow loses the escaping of $ and throws an exception, because $\_ is an invalid token (looks like its checking to make sure that \_ is a number, and obviously it isn't, but that check shouldn't happen since $ is escaped with \ )

**Comment by josephfrazier** [comment]
In replacement strings, `$` has to be escaped with another `$` instead of a `\`. Try this instead:

```js
XRegExp.replace('$_request', '\$_request', '$$_replacement')
```

See here for more details: http://xregexp.com/api/#replace

**Comment by slevithan** [comment]
@josephfrazier is correct, but note that there's an unnecessary backslash for the second (`search`) argument in his example (perhaps a typo since you'd need the backslash if the second argument was a regex). The second argument should either be `/\$_request/` or `'$_request'`.

If you wanted to include a literal backslash in the string you're searching for, you'd need to escape the backslash as `'\\$_request'`. See the "Regexes, strings, and backslashes" section at <http://xregexp.com/api/#XRegExp>.

**Comment by slevithan** [comment]
Note that XRegExp treating `$_` in replacement text as an error (rather than a literal `$_`) is a feature, to help catch mistakes early.

**Comment by joshbw** [comment]
Ah, thanks - I completely missed that.  Sorry for filing an issue when reading the docs would have sufficed.  Things work fine now
