### ISSUE TITLE
Multiline Anchors \A and \z

### ISSUE THREAD

**Issue by chadananda** [slevithan/xregexp#199]
As with Javascript regex, there does not seem to be any way to anchor at the beginning and end of a multiline string using \A and \z

 `SyntaxError: Invalid escape \A`

Is there another way to force a match to the entire multiline string?

For example, I want to identify (perhaps to trim) multiline whitespace from either side of a block of text with something like `\\A(\\s*?)(\\S[\\s\\S]*?)(\\s*?)\\z`.

**Comment by josephfrazier** [comment]
Since the XRegExp constructor returns a RegExp instance, and the JS regex engine doesn't support `\A` or `\z`, I'm not sure if there's a good way to support them in XRegExp while allowing `^` and `$` to be used with the `m` flag. However, if you don't need to use the `m` flag, you can simply use `^` and `$` instead. It looks like this is the case for your example:

Running this:

```js
' \n abc \n abc \n abc \n '.match(/^(\s*?)(\S[\s\S]*?)(\s*?)$/)
```

results in this:

```js
[ ' \n abc \n abc \n abc \n ',
  ' \n ',
  'abc \n abc \n abc',
  ' \n ',
  index: 0,
  input: ' \n abc \n abc \n abc \n ' ]
```

See here for more info: http://www.rexegg.com/regex-anchors.html#A

**Comment by slevithan** [comment]
You can add support for `\z` in XRegExp like this:

```
XRegExp.addToken(/\$/, () => '$(?!\\s)');
```

However, there is currently no way to emulate `\A` in JS due to lack of lookbehind support, so it can't yet be added to XRegExp.

**Comment by slevithan** [comment]
There are certainly ways though to only allow matches at the start of a string when you must use flag `/m` with your search regex.

One would be to match normally, check the index of the match, and reset the match to `null` if the match index isn't `0`.

Another might be to use flags `/ym` together if you only need to search for the first match. Then a `^` at the start of a regex would only match at the start of the string, while still allowing subsequent `^` matches (within the same regex) to match at the start of subsequent lines, depending on how the regex is written.

Or, just don't use flag `/m` (assuming you have control over the regexes used to search), and explicitly match newlines using `\r?\n` (or whatever line terminators you wish to support) so that you can reserve `^` for matching the start of the entire string.
