### ISSUE TITLE
Index of Named Capture

### ISSUE THREAD

**Issue by cpmcgrath** [slevithan/xregexp#217]
Hi,
Thanks for creating such a fantastic library. I've got a use case where I actually care about the Index of a named group more than the actual value. As far as I can see there's no way to get this at the moment. Is there anyway this could be added? Perhaps syntax such as

`parts.locationOf("x")`

**Comment by slevithan** [comment]
I would love to add this feature and think it would be super useful. Alas, JavaScript currently has no way to identify the string index of a backreference value, so this can't be done 100% reliably short of reimplementing the entire regex engine in JS or advancing a proposal through the TC39 committee for future JS versions.

That said, in most cases you can just search for the value within the overall matched string and add the index of your search to the overall regex match index. This assumes the string doesn't occur more than once in your match text and didn't occur outside of the match text altogether, since you can capture strings within lookahead that might not be a part of--or only partially overlap--the overall regex match. :-O And if the string you're looking for is unique within the overall subject text, then of course you can reliably find that position. Unfortunately these solutions are too context specific / unreliable to include them in the XRegExp API.
