### ISSUE TITLE
No support for IE8 due to using the keyword 'default'

### ISSUE THREAD

**Issue by Toldry** [slevithan/xregexp#230]
https://github.com/slevithan/xregexp/blob/614aba38a7cf14195280515e993b0cc82aa47fa2/src/xregexp.js#L1893

Attempting to run XRegExp on IE8 yields the following error:
`SCRIPT1010: Expected identifier`

This is due to the fact that the word `default` is used as a property name in various places in the code.

The same error can be reproduced by simply inputting the following snippet in IE8's console:

```
var foo = {};
foo.default = "bar"
```

Solution: Switch the property name to a something that isn't a keyword reserved by IE8 

If supporting IE8 isn't a goal in this project, please close this issue as irrelevant.

**Comment by josephfrazier** [comment]
Hi @Toldry, thanks for the report! Unfortunately, we decided to support only ES5-compatible browsers in https://github.com/slevithan/xregexp/issues/108, so IE8 is not a goal of the project.

If you're already using a transpiler like Babel in your project, you may be able to configure it to support IE8. Otherwise, you may be able to get away with downloading `xregexp-all.js` and replacing all instances of `.default` with `.defaultIE8` and instances of `default:` with `defaultIE8:`, but I haven't tested this myself.
