### ISSUE TITLE
Weird race condition? Performance drops dramatically / infinite loop

### ISSUE THREAD

**Issue by marcvoor** [slevithan/xregexp#245]
Hi,

We have an ASP.NET application with some HTML pages with an input field where users can enter a 
email address. To valid this address, we created a regex and use your library to valid the input.
We load `https://cdn.jsdelivr.net/npm/xregexp@4.0.0/xregexp-all.min.js` (I also tried it already with 4.1.1, but that gives the same result) and call the test function: `window.XRegExp(regexp).test(value)`
The regex we have is: `^([\w_%+-]+\.?)+@([\w-]+\.)+[a-zA-Z]{2,24}$`

By accident, I entered a totally wrong email address and that caused by Web browser to hang (I tried this with Chrome, IE, Edge, Firefox, all giving the same result).
The problem occurs when entering an invalid email address with only text (without the @) longer than 28 characters. E.g. copy paste this value: _VeryLongNameThatIsNoCorrectEmailAddress_.
In Chrome I checked the Performace monitor and saw that the CPU usage goes to 100%.

I took another test by entering invalid email addresses, starting with 20 characters, than 21, 22, etc. At a certain moment the regex evaluation slows down, and the CPU usage goes up, till it does not stop anymore (or it takes a looooot of time). See the image below.
![regexperformance](https://user-images.githubusercontent.com/22194094/39525856-77a5d59e-4e1d-11e8-8db0-32f70d61e506.jpg)

Can you have a look what is going on here?

Thanks

**Comment by slevithan** [comment]
Have you checked with `RegExp` rather than `XRegExp`? I'd expect you'll get the same result, since this is almost certainly a case a catastrophic backtracking. You can read about this at <https://www.regular-expressions.info/catastrophic.html>.

Although I haven't debugged this to verify, you'll most likely need to modify your regex pattern to address this, e.g. by using one of the email patterns described in depth at <https://www.regular-expressions.info/email.html>.
