### ISSUE TITLE
deprecated core-js@2.6.10

### ISSUE THREAD

**Issue by tdjastrzebski** [slevithan/xregexp#273]
Installing xregexp I get this warning
```
npm install xregexp --save
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**Comment by tdjastrzebski** [comment]
opss, the problem does not seem to be caused by xregexp

**Comment by bmarcotte** [comment]
I would recommend that this ticket be re-opened, as that deprecation warning is due to dependencies used in this package.  As long as xregexp depends on @babel/runtime-corejs2, it will depend on core-js@2, which causes that deprecation warning.  If this package could use @babel/runtime-corejs3 instead, that warning would go away.

**Comment by fchiumeo** [comment]
@tdjastrzebski 

this is a problem of xregexp [package.json](https://github.com/slevithan/xregexp/blob/master/package.json#L54)
