### ISSUE TITLE
u flag is needed for Astral characters but it causes trouble in Internet explorer

### ISSUE THREAD

**Issue by 70ray** [slevithan/xregexp#306]
For astral characters u flag is needed: e.g. XRegExp("^(?:[\n\r 𓀀-𓀂])$", "A");
Have to use XRegExp("^(?:[\n\r 𓀀-𓀂])$", "Au") but the u flag causes a javascript crash in Internet Explorer.

**Comment by slevithan** [comment]
XRegExp requires and defers to native handling for flag `u` and the astral ranges that `u` enables within character classes. As you mentioned, IE doesn't support flag `u` natively, so this won't work there.

Would it be possible to approach this a different way, using Unicode scripts, categories, blocks, or properties, rather than an explicit astral range? E.g. `XRegExp('^(?:\\p{EgyptianHieroglyphs}|[\n\r])$', 'A').test('𓀀');`

**Comment by 70ray** [comment]
Thanks for your reply. I came across the problem and thought I would mention it. It is not really a problem for us because, although we want to use Astral plane characters in the future and support IE for a short time now, we won't be doing both at the same time.
