### ISSUE TITLE
Question: Why an interpolated regex does not work

### ISSUE THREAD

**Issue by st-clair-clarke** [slevithan/xregexp#355]
I have the following that works:

```
export const phoneNorthAmerica = XRegExp.tag('nx')`
      ^\(?(?<area>      [2-9][0-8][0-9]  )\)?[-. ]?
          (?<exchange>  [2-9][0-9]{2}    )[-. ]?
          (?<station>   [0-9]{4}         )$
   `
```

The following does NOT work? Can you say why?

```
// the regex string above minus the anchors ^ and $
export const phoneNorthAmericaExpr = `
      \(?(?<area>      [2-9][0-8][0-9]  )\)?[-. ]?
          (?<exchange>  [2-9][0-9]{2}    )[-. ]?
          (?<station>   [0-9]{4}         )
   `

// The following interpolates the phoneNorthAmericaExpr, adding back the anchors ^ and $
// However, it does not work
export const phoneNorthAmerica = XRegExp.tag('nx')`
      ^${phoneNorthAmericaExpr}$
   `
```

Thanks

**Comment by slevithan** [comment]
Two issues:

The first is that, like in your issue #354, you forgot to either use `String.raw` or escape your backslashes in your string `phoneNorthAmericaExpr`.

The second is that, when you interpolate a string (rather than a regex) into an `XRegExp.tag` pattern, the string's special characters are escaped so that they are matched as literal characters. It is (literally) passed through `XRegExp.escape` (see [here](https://github.com/slevithan/xregexp/blob/5fb56c105150d27d4db307d13ed3656626403ddd/src/addons/build.js#L62)). This is documented, albeit not very clearly. The docs for [`XRegExp.tag`](https://xregexp.com/api/#tag) say "interpolated strings have their special characters escaped". In regular expression patterns, whitespace are special characters (that are escaped by `XRegExp.escape`) since their meaning changes depending on the presence of flag `x`.

The following would work without the unexpected gotcha, since it interpolates a regex rather than a string:

```js
const regex = XRegExp.tag('x')`^ ${/.../} $`;

// or
const regex1 = XRegExp('...');
const regex2 = /.../;
const regex3 = XRegExp.tag('x')`^ ${regex1} ${regex2} $`;
```

There is other documented but potentially unexpected behavior when interpolating. From the docs: "Interpolated patterns are treated as atomic units when quantified, interpolated strings have their special characters escaped, a leading `^` and trailing unescaped `$` are stripped from interpolated regexes if both are present, and any backreferences within an interpolated regex are rewritten to work within the overall pattern."

These behaviors all have their reasons and IMO are all desirable if understood and remembered. E.g., de-anchoring subpatterns allows embedding independently useful anchored regexes (and it almost never makes sense to interpolate a fully anchored pattern; you can double the anchors if you really need them). If I recall, the reasoning behind escaping interpolated strings is that errant special characters in a string such as a trailing unescaped backslash can break or change the meaning of the surrounding regex. But I've come to the opinion that the behavior of `XRegExp.tag` when interpolating is too magical/unexpected and it would be better to remove this behavior with the exception of rewriting backreferences for the overall pattern, which is clearly good/useful/powerful. Alas, changing the behavior would be a breaking change so is not likely to happen anytime soon, at least not without help from contributors via PRs. However, I've never seen people run into problems with the super-edge-case behavior/enhancements of interpolated regexes, so really it's just interpolated strings being escaped that is a potential gotcha.

To avoid this, I'd recommend just interpolating regexes (which you can create as native or XRegExp regexes) instead of strings.

**Comment by st-clair-clarke** [comment]
Thanks a million.  I am going through your book now, so I have not read everything as yet. So there will be some gotchas. The reason for my above gotcha is that the regex for a validation phone number and searching for a phone number in a documentation/text are quite similar as you pointed out in the book - the ^ and $ anchors are replaced with \b. I was trying NOT to repeat the common part of the regex twice.

I appreciate your help. Thanks again.

**Comment by slevithan** [comment]
Yeah, that's a great use case.

Alas, either use `XRegExp.build` (which doesn't automatically take raw strings so it's slightly less pretty than `.tag`) or store the reusable part of the pattern as a regex (rather than a string) if you want to use `.tag`.

Sorry for the unexpected surprise with escaped interpolated strings. :) Like I said above, even though it's intentional/documented, I wish I hadn't set it up that way.

**Comment by st-clair-clarke** [comment]
Thanks. I don't see it as s surprise though. I put it all to my lack of understanding Regex at the moment. I am getting better at it though. Thanks for your help.

**Comment by st-clair-clarke** [comment]
With your advice above, I have done some refactoring and will use this to deal with the dual regex needed when there is a difference in validation and searching docs. I do like the concept of tags though.

```
import { match } from 'ts-pattern'

export const phoneNorthAmericanRegex = ( searchType: string): RegExp | string => {
   const areaCode = XRegExp.tag('nx')`     (?<area>      [2-9][0-8][0-9]  )`
   const exchangeCode = XRegExp.tag('nx')` (?<exchange>  [2-9][0-9]{2}    )`
   const stationCode = XRegExp.tag('nx')`  (?<station>   [0-9]{4}         )`

   return match(searchType)
      .returnType<RegExp | string>()
      .with('validation', () => {
         return XRegExp.tag('nx')`
          ^\(? ${areaCode}     \)?[-. ]?
               ${exchangeCode} [-. ]?
               ${stationCode}  $`
      })
      .with('docs', () => {
         return XRegExp.tag('nx')`
          \b\(? ${areaCode}     \)?[-. ]?
               ${exchangeCode} [-. ]?
               ${stationCode}  \b`
      })
      .otherwise(
         () =>
            `Non-existent North America phone number with search option '${searchType}'`,
      )
}
```

**Comment by slevithan** [comment]
Cool. I like it.

Another option might be to have more generic functions like `withValidation` and `withBoundaries`. Ex:

```js
const withValidation = (regex) => {
  return XRegExp.tag('x' + regex.flags)`^  (?: ${regex} ) $`;
}
const withBoundaries = (regex) => {
  return XRegExp.tag('x' + regex.flags)`\b (?: ${regex} ) \b`;
}
```

I've included the non-capturing group `(?: ... )` so that it still works correctly if given a regex with top-level alternation like `/ab|cd/`.

Not saying this is better. Just throwing more ideas out there.

**Comment by st-clair-clarke** [comment]
I like it. It would be closer to what I originally thought about no repeating myself. Let me give it a try and see how it comes out. Ancient browsers is not a problem for what I am doing. So no fear.

**Comment by st-clair-clarke** [comment]
Love it after refactoring:

```
export const phoneNorthAmericanRegex = ( searchType = 'validation'): RegExp | string => {
   const areaCode = XRegExp.tag('nx')`     (?<area>      [2-9][0-8][0-9]  )`
   const exchangeCode = XRegExp.tag('nx')` (?<exchange>  [2-9][0-9]{2}    )`
   const stationCode = XRegExp.tag('nx')`  (?<station>   [0-9]{4}         )`
   
   const baseRegex = XRegExp.tag('nx')`
            \(? ${areaCode}     \)?[-. ]?
                ${exchangeCode} [-. ]?
                ${stationCode}  `
   
   return match(searchType)
       .returnType<RegExp | string>()
       .with('validation', () => {
          return XRegExp.tag('nx')`${withValidation(baseRegex)}`
       })
       .with('docs', () => {
          return XRegExp.tag('nx')`${withBoundaries(baseRegex)}`
       })
       .otherwise(
           () =>
               `Non-existent North America phone number with search option '${searchType}'`,
       )
}
```

Thanks

**Comment by st-clair-clarke** [comment]
After refactoring to include your latest suggestion:

```
export const phoneNorthAmericanRegex = ( searchType = 'validation'): RegExp | string => {
   const areaCode = XRegExp.tag('nx')`     (?<area>      [2-9][0-8][0-9]  )`
   const exchangeCode = XRegExp.tag('nx')` (?<exchange>  [2-9][0-9]{2}    )`
   const stationCode = XRegExp.tag('nx')`  (?<station>   [0-9]{4}         )`
   
   const baseRegex = XRegExp.tag('nx')`
            \(? ${areaCode}     \)?[-. ]?
                ${exchangeCode} [-. ]?
                ${stationCode}  `
   
   return match(searchType)
       .returnType<RegExp | string>()
       .with('validation', () => {
          return XRegExp.tag('nx')`${withValidation(baseRegex)}`
       })
       .with('docs', () => {
          return XRegExp.tag('nx')`${withBoundaries(baseRegex)}`
       })
       .otherwise(
           () =>
               `Non-existent North America phone number with search option '${searchType}'`,
       )
}

```
Great suggestion. Thanks.

**Comment by slevithan** [comment]
Cool, glad it was helpful. An observation though is that if you used my example functions without change, you don't need to wrap the regexes a final time with `XRegExp.tag` since the `withValidation` and `withBoundaries` functions already return regexes.

**Comment by st-clair-clarke** [comment]
Yep! You are correct. Made the adjustment. Thanks
