### ISSUE TITLE
Feature: Partial matching

### ISSUE THREAD

**Issue by mindplay-dk** [slevithan/xregexp#52]
Would it be possible to implement partial matching in XRegExp?

This would make real-time validation on web-forms far more user-friendly, as described in comments I posted on [this page](http://www.ng-newsletter.com/posts/validations.html#comment-959074323).

Java's Matcher class apparently supports it, as does [this Java library](http://codesaway.info/RegExPlus/partial.html) - a number of other libraries for PERL and C++ have this feature, but I was unable to find an implementation in JS.

One possible implementation strategy, would be to break down the expression to it's individual component expressions, then progressively compare a larger part of the total expression plus a `^` at the end of the expression - if you find a match, as far as I can figure, that should be a partial match. I don't know how difficult it would be to parse and break up the expression into component expressions...

Does this feature seem like a good fit for this library?

**Comment by slevithan** [comment]
Would be happy to see any pull requests that showed how this might work.

**Comment by mindplay-dk** [comment]
I'm not a regex expert, I wouldn't really know where to start... I can think of two ways to implement this, one as explained above, and alternatively, you'd need control of the actual regex engine, which I don't think you have, right? This is a bridge that adds features to Javascript's built-in regex engine? If you did have control of the actual engine, I guess all you'd need to do is return and indicate a partial match if you run out of input...

**Comment by slevithan** [comment]
> [Y]ou'd need control of the actual regex engine, which I don't think you have, right? This is a bridge that adds features to Javascript's built-in regex engine?

Yeah, that's correct.

> If you did have control of the actual engine, I guess all you'd need to do is return and indicate a partial match if you run out of input...

Yes, definitely. But doing this accurately for arbitrary complex regexes without access to the regex engine internals would be difficult (if it is possible) due to a variety of complexities, especially around alternation, grouping, and quantifiers.

> One possible implementation strategy, would be to break down the expression to it's individual component expressions, then progressively compare a larger part of the total expression plus a ^ at the end of the expression - if you find a match, as far as I can figure, that should be a partial match.

I presume you meant `$` instead of `^`. In fact you'd want to use `$(?!\s)` so that it works with flag `m`. But that aside, the presumption here of this working merely by trying additional tokens in order falls apart quickly with many example cases due to the problems presented by alternation, groupings, and quantifiers. You might be able to work around them, but it would not be trivial.

> I don't know how difficult it would be to parse and break up the expression into component expressions...

Tokenizing regex syntax is not hard. XRegExp is essentially already doing this via [xregexp.js#L50-L51](https://github.com/slevithan/xregexp/blob/7563982966f8606bfe79c3698efd4e355e2d775e/src/xregexp.js#L50-L51) (which is protected against invalid tokens with [xregexp.js#L1675-L1693](https://github.com/slevithan/xregexp/blob/7563982966f8606bfe79c3698efd4e355e2d775e/src/xregexp.js#L1675-L1693)).

**Comment by nhahtdh** [comment]
In Java, it's done by `hitEnd` function, which works by checking whether the execution of the regex ever reaches the end of the string. Of course, this requires access to regex internals, so the same idea can't be applied to XRegExp (unless it implements the whole engine in JS, which will be much less efficient).

**Comment by slevithan** [comment]
Closing since there's no plan for implementation. However, I remain interested in the idea.
