### ISSUE TITLE
Is there any way to accomplish this PCRE expression to XRegexp?

### ISSUE THREAD

**Issue by pocesar** [slevithan/xregexp#59]
I'm trying to convert this expression `'\(((?:(?>[^()]+)|(?R))*)\)'` in PCRE (PHP 5.4) to XRegexp, as I'm aware it doesn't suport lookaheads and the recursive `?R`. It doesn't matter if I need some extra code to get it working, but I'm failing hard to find a substitution for this.

**Comment by paztis** [comment]
in case I want information about all the nested blocks like below:
```
// Basic usage
var str = '(t((e))s)t()(ing)';
XRegExp.matchRecursive(str, '\\(', '\\)', 'g');
// -> ['t((e))s', '(e)', 'e', 'ing']
```


What do I need to pass as matchRecursive arguments ?

**Comment by slevithan** [comment]
@paztis, are you asking about how to use the `valueNames` option to get back extended details including match positions, matched delimiters, and segments between recursive matches? Take a look at the documentation, which shows a range of examples: https://xregexp.com/api/#matchRecursive

**Comment by paztis** [comment]
There's no example like this in the documentation. Only cases without real recursion are present.

The only way I've found is to call again by myself XRegExp.matchRecursive over the valueName 3.

Is there's a better way ?

Can you provide me a code example to resolve the exact case I propose on my post ?

**Comment by slevithan** [comment]
You did not propose anything close to an exact case in your comment -- you'd need to be much clearer or show inputs and exact expected outputs. And it's not clear what you mean by "real recursion."

I'm guessing that you either want `matchRecursive` to return:

1. An array of innermost matches of recursive patterns (rather than outermost matches, like it does), or
2. You want to return an array of nested matches, where each match item includes both the matched string and an array of nested match items at the next level down, and so on. I'm imaging the output might be something like this:

```js
[
  {
    match: 't((e))s(t)',
    nestedMatches: [
      {
        match: '(e)',
        nestedMatches: [
          {
            match: 'e',
            nestedMatches: []
          }
        ]
      },
      {
        match: 't',
        nestedMatches: []
      }
    ]
  },
  ...
]
```

Both of these potential alternatives sound possible to implement as your own wrapper functions that use `matchRecursive` under the hood.

> The only way I've found is to call again by myself XRegExp.matchRecursive over the valueName 3.
> 
> Is there's a better way ?

If I'm understanding you correctly, it might be best to run `matchRecursive` with flag `g` and without the `valueNames` option, then independently (and probably recursively) call `matchRecursive` again for each of the returned values, using independent match chains for each of the matches from your initial result and continuing down each chain until no more matches are found in any of the chains.

> Can you provide me a code example to resolve the exact case I propose on my post ?

You are asking for coding support on an old, unrelated issue. So I'm going to leave the conversation here.

**Comment by paztis** [comment]
HI

Yes I've resolved this problem through custom wrapper.
But the recursive name  in matchRecursive function let think it can discover nested patterns, while in reality it only discovers the top level ones.

**Comment by psygo** [comment]
I just don't get what the point is in naming a function as `matchRecursive` when it doesn't actually recurse.
