### ISSUE TITLE
better toString()

### ISSUE THREAD

**Issue by loveencounterflow** [slevithan/xregexp#70]
in https://github.com/loveencounterflow/xregexp3/commit/a81f8b292cee1813ffe33928a545720cd630b1b4, i try to make it so that, when printed to the console (in NodeJS, using `( require 'utils' ).inspect`), an `XRegExp` object is represented by its *input* pattern, not its compiled regular-JS representation. 

simple reason: i have to print out a lot of values that may contain `XRegExp` objects. when you combine a few advanced features, the output quickly gets incredibly long. for example, `var x = new XRegExp '^\\p{L}+$'; console.log( x )` will cause an output several hundred characters long that contains characters from scripts all around the world:
```
{ /^[A-Za-zªµºÀ-ÖØ-öø-ˁˆ-ˑˠ-ˤˬˮͰ-ʹͶͷͺ-ͽΆΈ-ΊΌΎ-ΡΣ-ϵϷ-ҁҊ ... ... ... ... ... ... ... ... ... ... 
```
which not only hides the intention of the pattern, it also makes the console (and the textarea i'm writing this in) grind to a halt (almost; i shortened the above quote for fear it could render this very page unusable). 

my uninformed patch seems to work when you do `console.log( x + '' )`, but not without adding that string literal. i think it would be much more helpful to have the input pattern displayed; as it stands, 

* most people will be unable to check the compiled pattern for correctness anyway, and
* the present output differs structurally from the output of a plain `RegExp` structurally already, so making it more readable and sensible would be a great idea IMHO.

**Comment by slevithan** [comment]
What if, instead of overriding `toString` (which might have some backcompat issues), regexes built or augmented by XRegExp had a documented property (perhaps `<regexp>.xregexp.source`) that you could read to get the input pattern? You could then manually set `XRegExp.prototype.toString` to read it in your own code, if you wanted to.

**Comment by slevithan** [comment]
I don’t expect to add `XRegExp.prototype.toString` in the base library, for a few reasons:

* This might be an edge case, but it would cause backcompat issues for anyone coercing XRegExps into strings.
* IMO it would have fairly low utility.
* I'm not sure how exactly the output should look.

However, in order to enable this for people like yourself who want access to the original source, in the attached commit I’ve added `<regex>.xregexp.source` and `<regex>.xregexp.flags` which now hold the original (pre-conversion) source and flags. I’ve also made `XRegExp.globalize` update the `<regex>.xregexp.flags` prop as appropriate, switched to explicitly using `RegExp.prototype.toString.call` in one case where I was previously using `String(regex)`, and started explicitly adding flag `A` in the XRegExp constructor when astral mode is installed (via `XRegExp.install('astral')`) so that it gets included in `<regex>.xregexp.flags`. All of this was needed to make it safe and easy to add your own `XRegExp.prototype.toString` method without inaccuracies in certain cases.

However, it’s still not clear exactly how `XRegExp.prototype.toString` should represent the output, due to differences between native regex syntax and XRegExp syntax. `RegExp.protoype.toString` outputs things like `"/./gim"` (with empty patterns replaced with `"(?:)"`, and forward slashes within the pattern escaped). However, that won't work for multiline XRegExps or XRegExps with unescaped forward slashes within embedded comments. Maybe you could return e.g. `"XRegExp('.', 'gim')"`, using something like this:

```
XRegExp.prototype.toString = function() {
  if (!XRegExp.isRegExp(this)) {
    throw new TypeError('Type RegExp expected');
  }
  if (this.xregexp && this.xregexp.source != null) {
    return (
      "XRegExp('" +
      this.xregexp.source.replace(/[\\']/g, '\\$&').replace(/\n/g, '\\n').replace(/\r/g, '\\r') +
      "', '" +
      (this.xregexp.flags || '') +
      "')"
    );
  }
  return RegExp.prototype.toString.call(this);
};
```

**Comment by slevithan** [comment]
Tests for the new `<regex>.xregexp.source` and `<regex>.xregexp.flags` properties were added in commits de197f8211d1015a9f5289b6f77ebbddee3866b2 and 75c7b2e4ff8151d7091dd1c760ed55a8af125c22.
