### ISSUE TITLE
add \Q\E Escaping support

### ISSUE THREAD

**Issue by SReject** [slevithan/xregexp#85]
As of current, block escaping([`\Q\E`](http://www.regular-expressions.info/characters.html#special)) is not supported and would be greatly appreciated if added. The usage allows for large blocks of text to be escaped without having to escape all 'dangerous' characters before compilation.

#### Rules:
Anything between `\Q` and the **first** encountered `\E` is seen as a string literal
`\Q` encountered within an open escape block should be interpreted as a literal "\Q"
`\E` is implied to be at the end of the pattern if not specified
`\\E` does **not** escape `\E` within escape blocks
`\E` encountered without a preceding open `\Q` should raise an error

#### Examples:

| Pattern | Matches | As |
| --- | --- | --- |
`\Qtext\E` | "text" | `/text/`
`\Q\Q\E` | "\Q" | /\\Q/
`\Qtext` | "text" | `/\Qtext\E/`
`\Qt.xt\E`  | "t.xt" | `/t\.xt/`
`\Q\\E` | "\" | `/\\/`
`text\E`| Erroneous

**Comment by slevithan** [comment]
Thanks for the excellent writeup, @SReject!

I'm not currently planning to add this, because I think this syntax is little known/used, and has a safer alternative: manual use of `XRegExp.escape` and concatenation. This is safer because it avoids problems if "\E" appears within the text you are embedding.

That said, XRegExp is designed to support 3rd party syntax addons, and this one is easy to add if it is useful for you:

```js
XRegExp.addToken(
  /\\Q([\s\S]*?)(?:\\E|$)/,
  function (match) {
    return XRegExp.escape(match[1]);
  },
  {scope: 'all'}
);

// Test it
XRegExp('^\\Q(?*+)').test('(?*+)'); // -> true
XRegExp('^\\Q.\\E.').test('.x'); // -> true
XRegExp('^\\Q.\\E.').test('xx'); // -> false

// XRegExp already throws for escaped letters without native functionality
// unless they are overridden by addons
XRegExp('\\E'); // -> Uncaught SyntaxError: Invalid escape \E
```

**Comment by mintern** [comment]
I implemented this support as an NPM module: <https://www.npmjs.com/package/xregexp-quotemeta>.
