### ISSUE TITLE
vulnerabilities and security issues

### ISSUE THREAD

**Issue by shirani182** [slevithan/xregexp#90]
Hello Steven,

Do you know about any vulnerabilities or security issues in Xregexp ?
Is this library still supported ? or EOL?
I sow version 3.0.0 published here but not the official website. Why is that?

Thank in advance,
Shiran

**Comment by slevithan** [comment]
I'm not aware of any security issues in XRegExp. No such issues have ever been reported. XRegExp is still supported and in development, although this has admittedly been very slow for a while now. There is no version 3.0.0 yet. There is the stable alpha "3.0.0-pre" here on GitHub, which I'd definitely recommend using over 2.0.0 since it includes the changes and improvements described at https://github.com/slevithan/xregexp/wiki/Roadmap . However, I've been waiting to update xregexp.com until V3.0.0 final is ready.
